name: just_sync
description: "A robust, flexible, and efficient solution for synchronizing data between a local Drift database remote Supabase Postgres database."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.35.3'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.29.0
  supabase_flutter: ^2.10.3
  logging: ^1.3.0
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  drift_dev: ^2.29.0
  mockito: ^5.5.1

flutter:
  uses-material-design: true
