name: Flutter test

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Flutter test
    runs-on: ubuntu-latest
    needs:
      - check-imports
      - build-runner
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2.21.0
        with:
          channel: "stable"
          cache: true

      - name: Clean
        run: flutter clean

      - name: Install and analyze
        run: |
          flutter pub get
          flutter analyze

      - name: Test
        run: flutter test -r github

      - name: Downgrade dependencies
        run: |
          flutter pub downgrade
          flutter analyze --no-fatal-infos --no-fatal-warnings